version: "3"
services:
  web:
    build:
      #specify where all the files and folders for this image
      #to be pulled from
      context: . #in this case current directory. if you have a project folder ex: reactprocect than this goes here
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      #mapping(:) the cuurent folder(.)outside of the container
      #to the folder inside the container(/app)
      - .:/app